[2023-12-28T20:27:55.862+0000] {processor.py:154} INFO - Started process (PID=4780) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:27:55.863+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:27:55.863+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:27:55.863+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:27:55.868+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:27:55.864+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    scheduled_interval=)
                       ^
SyntaxError: invalid syntax
[2023-12-28T20:27:55.869+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:27:55.891+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.032 seconds
[2023-12-28T20:28:01.907+0000] {processor.py:154} INFO - Started process (PID=4790) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:01.909+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:28:01.913+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:28:01.912+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:01.921+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:28:01.920+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    scheduled_interval=)''
                       ^
SyntaxError: invalid syntax
[2023-12-28T20:28:01.922+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:01.961+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.058 seconds
[2023-12-28T20:28:04.954+0000] {processor.py:154} INFO - Started process (PID=4791) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:04.955+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:28:04.955+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:28:04.955+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:04.957+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:28:04.956+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    scheduled_interval=)
                       ^
SyntaxError: invalid syntax
[2023-12-28T20:28:04.958+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:04.982+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.031 seconds
[2023-12-28T20:28:06.987+0000] {processor.py:154} INFO - Started process (PID=4792) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:06.988+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:28:06.989+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:28:06.989+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:06.991+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:28:06.991+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    scheduled_interval='')
                         ^
SyntaxError: invalid syntax
[2023-12-28T20:28:06.992+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:07.012+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.029 seconds
[2023-12-28T20:28:10.344+0000] {processor.py:154} INFO - Started process (PID=4798) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:10.345+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:28:10.345+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:28:10.345+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:10.347+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:28:10.346+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    scheduled_interval='@daily')
                               ^
SyntaxError: invalid syntax
[2023-12-28T20:28:10.348+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:10.381+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.040 seconds
[2023-12-28T20:28:22.405+0000] {processor.py:154} INFO - Started process (PID=4839) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:22.406+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:28:22.407+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:28:22.406+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:22.408+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:28:22.408+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    scheduled_interval='@daily', cat)
                                    ^
SyntaxError: invalid syntax
[2023-12-28T20:28:22.409+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:22.426+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.024 seconds
[2023-12-28T20:28:25.427+0000] {processor.py:154} INFO - Started process (PID=4849) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:25.427+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:28:25.428+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:28:25.428+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:25.430+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:28:25.429+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    scheduled_interval='@daily', catch)
                                      ^
SyntaxError: invalid syntax
[2023-12-28T20:28:25.430+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:25.447+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.022 seconds
[2023-12-28T20:28:28.469+0000] {processor.py:154} INFO - Started process (PID=4850) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:28.470+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:28:28.471+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:28:28.471+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:28.473+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:28:28.472+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    scheduled_interval='@daily', catchup=)
                                         ^
SyntaxError: invalid syntax
[2023-12-28T20:28:28.473+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:28.497+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.031 seconds
[2023-12-28T20:28:30.488+0000] {processor.py:154} INFO - Started process (PID=4851) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:30.489+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:28:30.489+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:28:30.489+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:30.492+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:28:30.490+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    scheduled_interval='@daily', catchup=False)
                                              ^
SyntaxError: invalid syntax
[2023-12-28T20:28:30.492+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:28:30.510+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.025 seconds
[2023-12-28T20:29:00.616+0000] {processor.py:154} INFO - Started process (PID=4916) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:29:00.617+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:29:00.617+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:29:00.617+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:29:00.619+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:29:00.619+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    scheduled_interval='@daily', catchup=False)
                                              ^
SyntaxError: invalid syntax
[2023-12-28T20:29:00.620+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:29:00.641+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.029 seconds
[2023-12-28T20:29:16.539+0000] {processor.py:154} INFO - Started process (PID=4957) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:29:16.540+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:29:16.540+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:29:16.540+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:29:16.542+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:29:16.541+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5
    scheduled_interval='@daily', catchup=False) as dag;
                                                      ^
SyntaxError: invalid syntax
[2023-12-28T20:29:16.543+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:29:16.559+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.023 seconds
[2023-12-28T20:29:19.810+0000] {processor.py:154} INFO - Started process (PID=4963) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:29:19.811+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:29:19.812+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:29:19.811+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:29:19.813+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:29:19.813+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T20:29:19.814+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:29:19.830+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.023 seconds
[2023-12-28T20:29:22.835+0000] {processor.py:154} INFO - Started process (PID=4973) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:29:22.837+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:29:22.837+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:29:22.837+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:29:22.842+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:29:22.841+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5, in <module>
    scheduled_interval='@daily', catchup=False) as dag:
TypeError: __init__() got an unexpected keyword argument 'scheduled_interval'
[2023-12-28T20:29:22.843+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:29:22.871+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.040 seconds
[2023-12-28T20:29:53.014+0000] {processor.py:154} INFO - Started process (PID=5030) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:29:53.015+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:29:53.015+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:29:53.015+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:29:53.017+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:29:53.017+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5, in <module>
    scheduled_interval='@daily', catchup=False) as dag:
TypeError: __init__() got an unexpected keyword argument 'scheduled_interval'
[2023-12-28T20:29:53.018+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:29:53.034+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.022 seconds
[2023-12-28T20:30:23.146+0000] {processor.py:154} INFO - Started process (PID=5094) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:30:23.147+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:30:23.148+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:30:23.148+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:30:23.150+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:30:23.149+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5, in <module>
    scheduled_interval='@daily', catchup=False) as dag:
TypeError: __init__() got an unexpected keyword argument 'scheduled_interval'
[2023-12-28T20:30:23.150+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:30:23.167+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.025 seconds
[2023-12-28T20:30:54.047+0000] {processor.py:154} INFO - Started process (PID=5159) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:30:54.048+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:30:54.049+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:30:54.049+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:30:54.051+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:30:54.050+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5, in <module>
    scheduled_interval='@daily', catchup=False) as dag:
TypeError: __init__() got an unexpected keyword argument 'scheduled_interval'
[2023-12-28T20:30:54.051+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:30:54.067+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.022 seconds
[2023-12-28T20:31:24.881+0000] {processor.py:154} INFO - Started process (PID=5215) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:31:24.881+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:31:24.882+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:31:24.882+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:31:24.884+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:31:24.883+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5, in <module>
    scheduled_interval='@daily', catchup=False) as dag:
TypeError: __init__() got an unexpected keyword argument 'scheduled_interval'
[2023-12-28T20:31:24.884+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:31:24.901+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.023 seconds
[2023-12-28T20:31:55.010+0000] {processor.py:154} INFO - Started process (PID=5280) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:31:55.011+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:31:55.012+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:31:55.012+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:31:55.014+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:31:55.013+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5, in <module>
    scheduled_interval='@daily', catchup=False) as dag:
TypeError: __init__() got an unexpected keyword argument 'scheduled_interval'
[2023-12-28T20:31:55.015+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:31:55.035+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.028 seconds
[2023-12-28T20:32:25.740+0000] {processor.py:154} INFO - Started process (PID=5344) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:32:25.740+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:32:25.741+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:32:25.741+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:32:25.743+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:32:25.742+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5, in <module>
    scheduled_interval='@daily', catchup=False) as dag:
TypeError: __init__() got an unexpected keyword argument 'scheduled_interval'
[2023-12-28T20:32:25.744+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:32:25.762+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.024 seconds
[2023-12-28T20:32:56.553+0000] {processor.py:154} INFO - Started process (PID=5408) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:32:56.554+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:32:56.555+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:32:56.555+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:32:56.557+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:32:56.556+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5, in <module>
    scheduled_interval='@daily', catchup=False) as dag:
TypeError: __init__() got an unexpected keyword argument 'scheduled_interval'
[2023-12-28T20:32:56.557+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:32:56.573+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.023 seconds
[2023-12-28T20:33:26.636+0000] {processor.py:154} INFO - Started process (PID=5463) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:33:26.637+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:33:26.638+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:33:26.637+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:33:26.640+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:33:26.639+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 5, in <module>
    scheduled_interval='@daily', catchup=False) as dag:
TypeError: __init__() got an unexpected keyword argument 'scheduled_interval'
[2023-12-28T20:33:26.640+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:33:26.657+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.024 seconds
[2023-12-28T20:33:45.743+0000] {processor.py:154} INFO - Started process (PID=5483) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:33:45.744+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:33:45.745+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:33:45.744+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:33:45.759+0000] {processor.py:766} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:33:45.927+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:33:45.927+0000] {manager.py:507} INFO - Created Permission View: can edit on DAG:user_processing
[2023-12-28T20:33:45.936+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:33:45.936+0000] {manager.py:507} INFO - Created Permission View: can delete on DAG:user_processing
[2023-12-28T20:33:45.942+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:33:45.942+0000] {manager.py:507} INFO - Created Permission View: can read on DAG:user_processing
[2023-12-28T20:33:45.942+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:33:45.942+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2023-12-28T20:33:45.956+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:33:45.956+0000] {dag.py:2606} INFO - Creating ORM DAG for user_processing
[2023-12-28T20:33:45.968+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:33:45.968+0000] {dag.py:3340} INFO - Setting next_dagrun for user_processing to 2023-12-27T00:00:00+00:00, run_after=2023-12-28T00:00:00+00:00
[2023-12-28T20:33:45.985+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.244 seconds
[2023-12-28T20:34:16.035+0000] {processor.py:154} INFO - Started process (PID=5547) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:34:16.035+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:34:16.036+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:34:16.036+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:34:16.051+0000] {processor.py:766} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:34:16.088+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:34:16.088+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2023-12-28T20:34:16.122+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:34:16.122+0000] {dag.py:3340} INFO - Setting next_dagrun for user_processing to 2023-12-27T00:00:00+00:00, run_after=2023-12-28T00:00:00+00:00
[2023-12-28T20:34:16.141+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.111 seconds
[2023-12-28T20:34:46.795+0000] {processor.py:154} INFO - Started process (PID=5602) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:34:46.796+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:34:46.797+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:34:46.797+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:34:46.814+0000] {processor.py:766} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:34:46.854+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:34:46.854+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2023-12-28T20:34:46.886+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:34:46.885+0000] {dag.py:3340} INFO - Setting next_dagrun for user_processing to 2023-12-27T00:00:00+00:00, run_after=2023-12-28T00:00:00+00:00
[2023-12-28T20:34:46.907+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.115 seconds
[2023-12-28T20:35:17.001+0000] {processor.py:154} INFO - Started process (PID=5666) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:35:17.001+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:35:17.002+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:35:17.002+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:35:17.016+0000] {processor.py:766} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:35:17.055+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:35:17.055+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2023-12-28T20:35:17.085+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:35:17.085+0000] {dag.py:3340} INFO - Setting next_dagrun for user_processing to 2023-12-27T00:00:00+00:00, run_after=2023-12-28T00:00:00+00:00
[2023-12-28T20:35:17.110+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.112 seconds
[2023-12-28T20:35:47.281+0000] {processor.py:154} INFO - Started process (PID=5728) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:35:47.282+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:35:47.283+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:35:47.283+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:35:47.305+0000] {processor.py:766} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:35:47.343+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:35:47.343+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2023-12-28T20:35:47.375+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:35:47.375+0000] {dag.py:3340} INFO - Setting next_dagrun for user_processing to 2023-12-27T00:00:00+00:00, run_after=2023-12-28T00:00:00+00:00
[2023-12-28T20:35:47.395+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.117 seconds
[2023-12-28T20:36:17.761+0000] {processor.py:154} INFO - Started process (PID=5785) to work on /opt/airflow/dags/user_processing.py
[2023-12-28T20:36:17.762+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-12-28T20:36:17.763+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:36:17.762+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-12-28T20:36:17.777+0000] {processor.py:766} INFO - DAG(s) dict_keys(['user_processing']) retrieved from /opt/airflow/dags/user_processing.py
[2023-12-28T20:36:17.809+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:36:17.809+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2023-12-28T20:36:17.840+0000] {logging_mixin.py:120} INFO - [2023-12-28T20:36:17.840+0000] {dag.py:3340} INFO - Setting next_dagrun for user_processing to 2023-12-27T00:00:00+00:00, run_after=2023-12-28T00:00:00+00:00
[2023-12-28T20:36:17.865+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.107 seconds
